<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WSRV01" name="com.randtronics.dpm.filemanager.executionEngine.Email_Test" tests="3" failures="1" timestamp="27 Sep 2016 12:07:42 GMT" time="106.661" errors="0">
  <testcase name="signOut" time="0.619" classname="com.randtronics.dpm.filemanager.executionEngine.Email_Test"/>
  <testcase name="Email_Valid" time="104.274" classname="com.randtronics.dpm.filemanager.executionEngine.Email_Test">
    <failure type="java.lang.AssertionError" message="Test2 failed with parameters: smtpout.asia.secureserver.net,465.0,test@randtronics.com,Yes,test@randtronics.com,qa@Angler123,null,Default (For Port 25)">
      <![CDATA[java.lang.AssertionError: Test2 failed with parameters: smtpout.asia.secureserver.net,465.0,test@randtronics.com,Yes,test@randtronics.com,qa@Angler123,null,Default (For Port 25)
	at org.junit.Assert.fail(Assert.java:88)
	at com.randtronics.dpm.filemanager.executionEngine.Email_Test.Email_Valid(Email_Test.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- Email_Valid -->
  <testcase name="signIn" time="1.768" classname="com.randtronics.dpm.filemanager.executionEngine.Email_Test"/>
</testsuite> <!-- com.randtronics.dpm.filemanager.executionEngine.Email_Test -->
